jobs:
- job: BuildAndTest
  displayName: Build and Test
  pool:
    vmImage: windows-2022
  steps:
  - ${{ if eq(variables['Build.SourceBranch'], 'refs/heads/master') }}:
    - task: PowerShell@2
      displayName: Get Version from Directory.Build.props
      inputs:
        targetType: inline
        script: |
          $xml = [Xml] (Get-Content .\src\Directory.Build.props)

          $version = [String] $xml.Project.PropertyGroup.Version
          $version = $version.Trim()

          Write-Host "##vso[task.setvariable variable=Version;]$version"
  - ${{ else }}:
    - task: PowerShell@2
      displayName: Get Version from Directory.Build.props
      inputs:
        targetType: inline
        script: |
          $xml = [Xml] (Get-Content .\src\Directory.Build.props)

          $version = [String] $xml.Project.PropertyGroup.Version
          $version = $version.Trim()

          Write-Host "##vso[task.setvariable variable=Version;]$version-alpha-$(Build.BuildNumber)"

  - task: DotNetCoreCLI@2
    displayName: dotnet build
    inputs:
      projects: src/System.Activities.sln
      arguments: --configuration $(BuildConfiguration) -p:Version="$(Version)"

  - task: DotNetCoreCLI@2
    displayName: dotnet test
    inputs:
      command: test
      projects: src
      arguments: --no-build --configuration $(BuildConfiguration) --collect "Code Coverage" --settings src/CodeCoverage.runsettings

  - task: CopyFiles@2
    displayName: 'Copy Files to: Build.ArtifactStagingDirectory'
    inputs:
      SourceFolder: src
      Contents: |
        CoreWf\bin\$(BuildConfiguration)\*.*nupkg
        UiPath.Workflow\bin\$(BuildConfiguration)\*.*nupkg
      TargetFolder: $(Build.ArtifactStagingDirectory)
      CleanTargetFolder: true

  - task: PublishBuildArtifacts@1
    displayName: Publish Artifacts
    inputs:
      ArtifactName: $(ArtifactName)
